apiVersion: apps/v1
kind: Deployment
metadata:
  name: flasktask
  labels:
    app: flasktask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flasktask
  template:
    metadata:
      labels:
        app: flasktask
    spec:
      containers:
        - name: mastertask
          image: tahmid55/flask-docker-image:latest
          ports:
            - containerPort: 5000
          imagePullPolicy: Always